services:
  - type: web
    name: acebook-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          name: acebook-db
          type: database
          property: connectionString
      - key: DATABASE_USERNAME
        fromService:
          name: acebook-db
          type: database
          property: user
      - key: DATABASE_PASSWORD
        fromService:
          name: acebook-db
          type: database
          property: password
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar app.jar"

  - type: postgresql
    name: acebook-db
    plan: free
    properties:
      databaseName: acebook_postgres_development
      user: acebook_user
      password: acebook_password