name: CI/CD Pipeline

on:
  push:
    branches:
      - deployment-pipeline
  pull_request:
    branches:
      - deployment-pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: acebook-springboot
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'  # Options: 'temurin', 'zulu', 'adopt', etc.
          architecture: x64
          check-latest: false

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test