name: CI/CD Pipeline

on:
  push:
    branches:
      - deployment-pipeline
  pull_request:
    branches:
      - deployment-pipeline

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: acebook-springboot
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          architecture: x64
          check-latest: false

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          sudo apt-get install -yqq unzip
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test