name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: acebook_springboot_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mhk1/acebook_penguins:latest

      - name: Set up PostgreSQL container
        run: |
          docker run -d --name acebook_postgres -p 5432:5432 \
          -e POSTGRES_DB=acebook_springboot_development \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=password postgres:latest

      - name: Wait for PostgreSQL to start
        run: sleep 20

      - name: Run Tests
        run: |
          ./mvnw test