name: CI

on:
  push:
    branches:
      - main
      - test-ci-cd-workflow
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
            docker build -t my-image:latest .
            docker push my-image:latest

      - name: Start PostgreSQL container
        run: |
          docker run -d --name postgres \
            -e POSTGRES_DB=${{ secrets.local_db }} \
            -e POSTGRES_USER=${{ secrets.local_user }} \
            -e POSTGRES_PASSWORD=${{ secrets.local_password }} \
            -p 5432:5432 postgres:latest

      - name: Build the application
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Run application and verify
        run: |
          docker run -d --name acebook_penguins \
            -p 8080:8080 mhk1/acebook_penguins:latest
          echo "Waiting for the application to start..."
          sleep 30
          curl -f http://localhost:8080/login || (docker logs acebook_penguins && exit 1)